config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries


  root 'breweries#index'

  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
 

  post 'places', to: 'places#search'

  delete 'signout', to: 'sessions#destroy'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
end

app/models/style.rb
class Style < ApplicationRecord
  has_many :beers
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: %i[show edit update destroy]

  # GET /styles or /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1 or /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles or /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to style_url(@style), notice: "Style was successfully created." }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1 or /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to style_url(@style), notice: "Style was successfully updated." }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1 or /styles/1.json
  def destroy
    @style.destroy

    respond_to do |format|
      format.html { redirect_to styles_url, notice: "Style was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_style
    @style = Style.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def style_params
    params.require(:style).permit(:name, :description)
  end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_with(model: style) do |form| %>
  <% if style.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
        <% style.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/styles/_style.html.erb
<div id="<%= dom_id style %>">
  <p>
    <strong>Name:</strong>
    <%= style.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= style.description %>
  </p>

  <p>
    <strong>Beers:</strong>
    <% style.beers.each do |beer| %>
      <%= link_to "#{beer.name}", beer %>
    <% end %>
  </p>

</div>

app/views/styles/edit.html.erb
<h1>Editing style</h1>

<%= render "form", style: @style %>

<br>

<div>
  <%= link_to "Show this style", @style %> |
  <%= link_to "Back to styles", styles_path %>
</div>

app/views/styles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Styles</h1>

<div id="styles">
  <% @styles.each do |style| %>
    <%= render style %>
    <p>
      <%= link_to "Show this style", style %>
    </p>
  <% end %>
</div>

<%= link_to "New style", new_style_path %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render "form", style: @style %>

<br>

<div>
  <%= link_to "Back to styles", styles_path %>
</div>

app/views/styles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @style %>

<div>
  <%= link_to "Edit this style", edit_style_path(@style) %> |
  <%= link_to "Back to styles", styles_path %>

  <%= button_to "Destroy this style", @style, method: :delete %>
</div>